### ISSUE TITLE
Repeated sound doesn't works in Safari (iOS and macOS)

### ISSUE THREAD

**Issue by romanzaycev** [surikov/webaudiofont#1]
All sounds played only one time.
Tested with: desktop (macOS 10.11.6) Safari (9.1.3) and IOS (10.1) Safari.

Log:
`[Log] WebAudioFont Player v1.06 (WebAudioFontPlayer.js, line 1)`
`[Log] load _tone_Accoustic_32Bsaccousticbs_461_460_45127 (32.0.Accoustic_32Bsaccousticbs_461_460_45127.js, line 1)`
`[Error] InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable.
    stop (WebAudioFontPlayer.js:89)
    findEnvelope (WebAudioFontPlayer.js:89)
    queueWaveTable (WebAudioFontPlayer.js:16)
    global code (WebAudioFontExampleSimple.html:1)`

Звук в примерах проигрывается только один раз, повторное нажатие вызывает ошибку.

**Comment by surikov** [comment]
fixed
