### ISSUE TITLE
Random empty buffer at the first time the note is played

### ISSUE THREAD

**Issue by ghost** [surikov/webaudiofont#10]
Hello,

I have a weird issue about empty buffer when i played a note for the first time (it's random issue, like 1/5).

![empybuffer](https://user-images.githubusercontent.com/17066847/30420084-ce6f4562-9938-11e7-831f-f20bfd15620b.jpg)

If i replay this note after that, this work fine.

This issue appear on all browsers (Chrome, Firefox, Safari) and all device (desktop, tablet, mobile).
I create 6 instances of WebAudioFontPlayer (one per instrument, like MIDI channel) like this :
  

```
this.audioContext = ctx;
this.player = new WebAudioFontPlayer();

if(this.supportOGG == true){
                this.player.loader.startLoad(this.audioContext, this.listeInstruments[preset]["url"], _this.listeInstruments[preset]["object"]);
		this.player.loader.waitOrFinish(_this.listeInstruments[preset]["object"],function(){
					_this.selectedPreset = window[_this.listeInstruments[preset]["object"]];
					_this.selectedPresetString = preset;
		});
}else{
	var head = document.getElementsByTagName("head")[0];
	var script = document.createElement("script");
	script.src = this.listeInstruments[preset]["url"];
	var done = false;
	script.onload = script.onreadystatechange = function() { 
			// attach to both events for cross browser finish detection:
		if ( !done && (!this.readyState ||this.readyState == "loaded" || this.readyState == "complete") ) {
			done = true;
			_this.selectedPreset = window[_this.listeInstruments[preset]["object"]];
			_this.selectedPresetString = preset;
			// cleans up a little memory:
			script.onload = script.onreadystatechange = null;
			head.removeChild(script);
		}
	};
	head.appendChild(script);
}
```

Thank in advance ;)

**Comment by surikov** [comment]
Use decodeAfterLoading to parse sound before use it.

Example:

&lt;html&gt;
	&lt;head&gt;
		&lt;script src='https://surikov.github.io/webaudiofont/npm/dist/WebAudioFontPlayer.js' &gt;&lt;/script&gt;
		&lt;script src='https://surikov.github.io/webaudiofontdata/sound/0000_JCLive_sf2_file.js' &gt;&lt;/script&gt;
        &lt;script src='https://surikov.github.io/webaudiofontdata/sound/0140_GeneralUserGS_sf2_file.js' &gt;&lt;/script&gt;
		&lt;script&gt;
			var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
			var audioContext = new AudioContextFunc();
			var player=new WebAudioFontPlayer();
            player.loader.decodeAfterLoading(audioContext,'_tone_0000_JCLive_sf2_file');
            player.loader.decodeAfterLoading(audioContext,'_tone_0140_GeneralUserGS_sf2_file');
            player.loader.waitLoad(function(){
              console.log('You can play music now.');
            });
		&lt;/script&gt;
	&lt;/head&gt;
	&lt;body&gt;
		&lt;p&gt;&lt;a href="#" onmousedown="player.queueWaveTable(audioContext, audioContext.destination, _tone_0000_JCLive_sf2_file, 0, 55, 3.5);"&gt;Play piano&lt;/a&gt;&lt;/p&gt;
		&lt;p&gt;&lt;a href="#" onmousedown="player.queueWaveTable(audioContext, audioContext.destination, _tone_0140_GeneralUserGS_sf2_file, 0, 55-12, 3.5);"&gt;Play bell&lt;/a&gt;&lt;/p&gt;
	&lt;/body&gt;
&lt;/html&gt;

See live page
http://jsbin.com/nihiveroga/edit?html,console,output

**Comment by ghost** [comment]
Great, it seems to working fine now.

Thanks !
