### ISSUE TITLE
Where is the code to generate this format?

### ISSUE THREAD

**Issue by chr15m** [surikov/webaudiofont#100]
It would be great to be able to convert existing sf2 files to this JSON format. Is it possible to share the code you used to do that? I couldn't find it in the repository. Thanks so much!

**Comment by surikov** [comment]
https://github.com/surikov/webaudiofont/issues?q=soundfont

**Comment by chr15m** [comment]
Solution for anybody who finds this in the future. There is a great JavaScript library called [soundfont2](https://github.com/Mrtenz/soundfont2) which will let you extract the data and raw audio from an sf2 file in the browser or Node.js.

Here's an example in Node:

```javascript
import * as fs from 'fs';
import { SoundFont2 } from 'soundfont2';

// Do not specify any encoding type
const buffer = fs.readFileSync('my-soundfont.sf2');
const soundFont = new SoundFont2(buffer);
```

**Comment by surikov** [comment]
soundfond2 is incompatible with WebAudioFont.
See data structure at https://github.com/surikov/webaudiofont/blob/master/npm/src/otypes.ts#L26
Please don't post wrong information.

Please read more at https://github.com/surikov/webaudiofont/issues?q=soundfont

**Comment by chr15m** [comment]
No worries. I have updated my comment to remove the sentence about generating the same format as this repo. You can of course still use that library to extract the data and audio from an sf2 file, which is what I was looking for in the first place.
