### ISSUE TITLE
Using instruments in DAW apps (Reaper)

### ISSUE THREAD

**Issue by popstas** [surikov/webaudiofont#102]
Hello, I want to record some of midi drum beats in Cocos Reaper and play it in my web app.

At this time I'm using slightly different instruments in Reaper and in the web app.
I need to export file to midi first if I want to hear final sound.

Is it possible to use webaudiofont instrument in Reaper?

I'm using this drums in the web app - https://surikov.github.io/webaudiofontdata/sound/drums_0_JCLive_sf2_fileStandard_part2_.html

**Comment by surikov** [comment]
I don't know anything about Cocos Reaper
