### ISSUE TITLE
Clicks at the start of sound.

### ISSUE THREAD

**Issue by vnams** [surikov/webaudiofont#104]
First, thanks for this software. It's very useful.

I am making a myCustomSampledInstrument using the instructions given in 
https://surikov.github.io/webaudiofont/examples/customsample.html. 
I have two issues:

1) Minor issue: I can make a custom sampled instrument using .wav files, but not .mp3 or .ogg files. 

2) Major issue: When I make a custom sampled instrument then there is an audible click at the start of the sound. To test whether that is part of my sound file, I inserted a blank space at the start. I then heard the click, then no sound and then my sound. So the click has something to do with Webaudiofont. Likely you can't hear clicks for the instruments in the library because they all start with some articulation, which would hide the clicks.

How can I remove the click?

Thanks

**Comment by surikov** [comment]
> So the click has something to do with Webaudiofont

No.

Listen to example at 
https://surikov.github.io/webaudiofont/examples/customsample.html
for instrument -1.

There are no clicks.

Audio editing is a difficult task.
You can distort the sound even when you change the sampling ratio or cut silence from an audio file.
I don't know what you make the instrument out of.

I can't help you without complete information.
