### ISSUE TITLE
How to dynamically decay a drum - in particular the open Hi-Hat

### ISSUE THREAD

**Issue by markoliverbrawn** [surikov/webaudiofont#107]
**Is your feature request related to a problem? Please describe.**
Not really a major problem. The drums work really well generally. The issue I'm facing is how to decay the open hi-hat as if closed by the pedal. Currently it rings past the pedal, so doesn't make a convincing open/to/closed hi-hat sound. 

**Describe the solution you'd like**
If there was a decay parameter, I could programatically decay it based on the difference between it's "when" and a subsequent HHPedal "when".

**Describe alternatives you've considered**
A volume envelope might possible, but the API seems quite complex, so I wondered if I was missing something.

**Additional context**
-

**Comment by surikov** [comment]
Use custom AHDSR envelope for the sample. Look to source of example here
https://surikov.github.io/webaudiofont/examples/ahdsr.html

**Comment by markoliverbrawn** [comment]
Thanks, but that doesn't really answer the question.

**Comment by surikov** [comment]
This is an exact solution for the audio sample duration.
