### ISSUE TITLE
window.requestAnimationFrame pauses playback when switching tabs in firefox/chrome?

### ISSUE THREAD

**Issue by allen-munsch** [surikov/webaudiofont#108]
**Is your feature request related to a problem? Please describe.**

- https://github.com/surikov/webaudiofont/blob/f78c01197a313560475d00d371709d6d3d3cac97/npm/src/ticker.ts#L61

Any ideas on how to get the ticker to work when I switch tabs?

**Describe the solution you'd like**

Switch tab, continues to play

**Describe alternatives you've considered**

document.hidden and visibilitychange pause

**Additional context**

- https://github.com/allen-munsch/xtreme-midi-player

**Comment by surikov** [comment]
read this
https://github.com/surikov/webaudiofont/issues/106
