### ISSUE TITLE
Slide

### ISSUE THREAD

**Issue by RayckSantos** [surikov/webaudiofont#109]
Hello!!!
Could you help me with the slide? 

function playNote(){
    player.queueWaveTable(audioContext, audioContext.destination, _tone_0250_SoundBlasterOld_sf2, 0, 52, 1, 1, /*example*/);
}

this is a function that i'm using.

how do I make a slide from note 52 to note 55?

**Comment by surikov** [comment]
Reas docs here
https://surikov.github.io/webaudiofont/npm/src/docs/classes/player.WebAudioFontPlayer.html#queueWaveTable

```
let slide=[{delta:3,when:0.5]};
player.queueWaveTable(audioContext, audioContext.destination, _tone_0250_SoundBlasterOld_sf2, 0, 52, 1, 1, slide);

```
live example
https://surikov.github.io/webaudiofont/examples/mixer.html
- look to page source

**Comment by RayckSantos** [comment]
very very thank!!


Em sáb., 9 de nov. de 2024 às 10:36, Srgy Surkv ***@***.***>
escreveu:
