### ISSUE TITLE
under what license are these distributed?

### ISSUE THREAD

**Issue by walterbender** [surikov/webaudiofont#11]
I have a FOSS project and hence I cannot incorporate non-FOSS content. It was not obvious what license you are using to distribute these soundfonts.

**Comment by walterbender** [comment]
Sorry. I did not see the MIT license in the repo. Maybe reference it in the README file?

**Comment by surikov** [comment]
[done](https://github.com/surikov/webaudiofont/commit/67051be2911422fadb73f03056296b5686d95806)

**Comment by mk-pmb** [comment]
Update: Nowadays it's GPL v3 (apparently since 2020-01-16), see #57.
