### ISSUE TITLE
Possible to cancel a single sound via an event vs. audioContext in total?

### ISSUE THREAD

**Issue by marcaaron** [surikov/webaudiofont#12]
Leveraging this library to create a text keyboard based instrument and I'm wondering if it's possible to cancel a queued up / currently playing sound via say a 'keyup' or some other event? I see that we can predetermine the overall length of the sound via the duration argument at the time of calling queueWaveTable and I've played around with the cancelQueue function on the player by passing it the audioContext. This worked, but canceled _all_ of my currently playing notes. Is there some way I can target a specific sound that has been queued? 

Oh and thanks for this! Having so much damn fun over here! 👍

**Comment by surikov** [comment]
queueWaveTable returns envelope for note. You can invoke
envelope.cancel();
to stop note at any time.

Open example 'endless flute'
http://jsbin.com/midadem/1/edit?html,output
look to playPipe and stopPipe

Look to 
https://surikov.github.io/midi-sounds-react-examples/examples/midi-sounds-example10/build/
if you use ReactJS

**Comment by marcaaron** [comment]
Cool! Thanks! Since opening this I also noticed that envelopes get saved in the player.envelopes array and can be cancelled from there as well.
