### ISSUE TITLE
Using custom sound fonts 

### ISSUE THREAD

**Issue by robertcapsure** [surikov/webaudiofont#14]
Hey! Amazing project! I was wondering how can I use this library with custom sound fonts. I see where I can add raw data? But I’m not sure what that means and how I would convert a sound font or wave to raw data

**Comment by surikov** [comment]
see tutorial at https://surikov.github.io/webaudiofont/examples/customsample.html

**Comment by grahamglover** [comment]
I have a soundfont (sf2) file with 127 presets that would like to load with webaudiofont. Do I need to convert each of the 127 presets according to the tutorial? Or is there another way? love your work!

**Comment by surikov** [comment]
WebAudioFont consists of many presets for each of 127 GM instruments.
Use any of them.

There are no public converter for SF2 files.

**Comment by grahamglover** [comment]
Have need to load sf2 into a client page.... Your solution is the closest.

**Comment by grahamglover** [comment]
I will try right a converter to put my sf2 in the format required, as documented in your tutorial.  I can likely use the sf2parser provided in the sf2synth project.  Thanks.

**Comment by mk-pmb** [comment]
@grahamglover 

> I will try right a converter to put my sf2 in the format required,

Did it work? If not, you can try [my converter](https://github.com/mk-pmb/midijssf-from-sf2-pmb).
