### ISSUE TITLE
Glitch sound when using queueWaveTable

### ISSUE THREAD

**Issue by weiwei-ww** [surikov/webaudiofont#15]
Hi, I am using webaudiofont to build a midi player. However, when I used queueWaveTable to play notes, it contained some glitch sound. I tried the example midi player [here](https://surikov.github.io/webaudiofont/examples/midiplayer.html) which does not give any glitch sounds. I wonder if there are any 'tricks' to eliminate them.

**Comment by surikov** [comment]
Create example that reproduces your problem and add link to this issue.

There are no tricks.

**Comment by weiwei-ww** [comment]
I tried not using the maximum volume which solved the problem. Any clues why this can eliminate the glitch sound?

**Comment by surikov** [comment]
I don't see your code. No answer without code example, sorry/
