### ISSUE TITLE
how to generate custom instrument file?

### ISSUE THREAD

**Issue by edu4024** [surikov/webaudiofont#18]
How to generate custom instrument file with all parameters(originalPitch, keyRangeLow, keyRangeHigh, loopStart, loopEnd, coarseTune, fineTune, sampleRate, ahdsr, sample) and all 88 notes for each zone?

**Comment by surikov** [comment]
See https://github.com/surikov/webaudiofont#custom-samples

**Comment by edu4024** [comment]
Hot to generate it in auto mode, not manual?
