### ISSUE TITLE
How do I pause the Midi Demo?

### ISSUE THREAD

**Issue by rlb222** [surikov/webaudiofont#19]
I'm trying to use the [Midi demo](
https://surikov.github.io/webaudiofont/examples/midiplayer.html) and would like to add a [Pause] button.

I have added a 
`var isPaused = false`
and used it in the startPlay() function for the two setInterval().

Example:
```
setInterval(function () {
  if ((!isPaused) && (audioContext.currentTime > nextStepTime - stepDuration)) {code}
``` 

But this is not the complete solution, because when un-pausing it again, it starts going very fast to make up for the lost time.
This is because `audioContext.currentTime` is not paused I think.

Can you please help me in pausing it properly?
Thanks!
René

**Comment by surikov** [comment]
recalculate nextStepTime before start again.

**Comment by rlb222** [comment]
I added an extra line and it worked!

```
if (isPaused) {
   nextStepTime = audioContext.currentTime + stepDuration;
}
```

Thank you!
René

**Comment by ghost** [comment]
Dear rlb222,
Could you please provide me modified code including "pause" button? Thanks for your help.

**Comment by ghost** [comment]
I've applied your solution and working well.
Thanks

**Comment by rlb222** [comment]
Great! And the midi code on my website is also still running nicely. Thx!
