### ISSUE TITLE
How do I show the MetaEvent Track Name in the Midi Demo?

### ISSUE THREAD

**Issue by rlb222** [surikov/webaudiofont#20]
On screen in the Midi Demo, I want to show the (event meta) **track name** next to the instrument. 
`MIDIEvents.EVENT_META_TRACK_NAME:`

I haven't yet found it in the objects (in the inspector with console.log) when I am running `play.html`.

Hope you can **help me find the track name**.
I have found references of `.EVENT_META_TRACK_NAME`  in `midifile.js` but it's not clear how I can get these into the objects of `play.html`.

Thank you for your help!
René

**Comment by surikov** [comment]
WebAudioFont doesn't use this event.
