### ISSUE TITLE
Empty buffer object

### ISSUE THREAD

**Issue by pomarbar** [surikov/webaudiofont#23]
I´m trying to use your webaudiofont in my AddMIDIweb app. I select only a few instruments to sound. But when I start the page the buffer of instrument is empty and I have to click twice the play buttom to load an instrument for the first time. There is something wrong with my code but what is it? Can you help me? Thanks for your time.

**Comment by surikov** [comment]
Open source of simple example at [https://surikov.github.io/webaudiofont/examples/simple.html](https://surikov.github.io/webaudiofont/examples/simple.html)

Look to the row
`player.loader.decodeAfterLoading(audioContext, '_tone_0000_JCLive_sf2_file');`

Better solution: load instruments in realtime. See example at [https://surikov.github.io/webaudiofont/examples/dynamic.html](https://surikov.github.io/webaudiofont/examples/dynamic.html)

**Comment by pomarbar** [comment]
Thanks a lot for your reply. I´m mixing playNote and dinamic examples. I cancel automatic play pasing it to the buttom play. I am loading the instrument thru a variable, not directly, like in dinamic.html example. The first time the console reports an empty buffer and can´t play the sequence of notes. The next time has no problem. When I change the instrument reports an empty buffer too, only for the first time.  Why does this happen?

**Comment by surikov** [comment]
Create example at CodePen and paste link here.

**Comment by pomarbar** [comment]
First version, change instrument requires a second click on PLAY for the first time.
https://codepen.io/pomarbar/pen/RegZxq

**Comment by pomarbar** [comment]
Second version: don´t require a second click on PLAY but can´t change instrument, only works with index = 0 :
https://codepen.io/pomarbar/pen/RegZev

**Comment by surikov** [comment]
Fixed code

```javascript
var index = 0;
var instrumento = [
	//_tone_0010_GeneralUserGS_sf2_file, //Piano
	//_tone_0090_JCLive_sf2_file //Carrillón
];
//var nombreFileInstr = ['_tone_0010_GeneralUserGS_sf2_file', '_tone_0090_JCLive_sf2_file '];
//var urls = ['https://surikov.github.io/webaudiofontdata/sound/0010_GeneralUserGS_sf2_file.js',
//	'https://surikov.github.io/webaudiofontdata/sound/0090_JCLive_sf2_file.js'
//];
var selectedPreset = null; //instrumento[index];
var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
var audioContext = new AudioContextFunc();
var player = new WebAudioFontPlayer();

//Piano
var info = player.loader.instrumentInfo(14);
player.loader.startLoad(audioContext, info.url, info.variable);
player.loader.waitLoad(function() {
	console.log('done', info);
	instrumento[0] = window[info.variable];
	player.loader.decodeAfterLoading(audioContext, info.variable);

	selectedPreset = instrumento[0];
	
	//Carrillón
	var info2 = player.loader.instrumentInfo(103);
	player.loader.startLoad(audioContext, info2.url, info2.variable);
	player.loader.waitLoad(function() {
		console.log('done', info2);
		instrumento[1] = window[info2.variable];
		player.loader.decodeAfterLoading(audioContext, info2.variable);
	});
});
var listaSons = [
	[0, 60, 1, 0.5],
	[0.4, 63, 1, 0.5],
	[0.8, 67, 1, 0.5],
	[1.2, 71, 1, 0.5],
	[1.6, 72, 1, 0.5]
];
var numInstr = [15, 104, 127, 191, 228, 252, 577, 589, 629, 713, 755, 772, 792];

//player.loader.decodeAfterLoading(audioContext, nombreFileInstr[index]);

function tocar() {
	var tiempo = audioContext.currentTime;
	for (var i = 0; i < listaSons.length; i++) {
		var ltemp = listaSons[i];
		var mm = tiempo + ltemp[0];
		player.queueWaveTable(audioContext, audioContext.destination, selectedPreset, mm, ltemp[1], ltemp[2], ltemp[3]);
	};
}

function instrumentoSel() {
	index = parseInt(document.getElementById("OS").selectedIndex);
	//player.loader.startLoad(audioContext, urls[index], nombreFileInstr[index]);

	//player.loader.waitLoad(function() {
	//	player.cancelQueue(audioContext);
	//});
	selectedPreset = instrumento[index];
	console.log('select', index, selectedPreset);
}
```
Live example
https://codepen.io/sss1024/pen/pxwpLy

**Comment by pomarbar** [comment]
Really, really impressive, thanks for your kind reply. This code works perfect. This is 'the sound solution´ for my music education apps. You will hear from them soon. God bless you for share your knowledge.
