### ISSUE TITLE
How to play a MIDI file encoded in base64

### ISSUE THREAD

**Issue by sujinleeme** [surikov/webaudiofont#24]
Hello, is there a way to play a MIDI file/string encoded in base64?
`data:audio/midi;base64,TVRoZAAAAAYAAQADAHhNVHJrAAAACwD/`

**Comment by sujinleeme** [comment]
Sorry to make a disturbance. 
What I found a solution is :
 delete `data:audio/midi;base64` and then convert base64(`TVRoZAAAAAYAAQADAHhNVHJrAAAACwD`) to ArrayBuffer and it works. :)

**Comment by surikov** [comment]
yes. See source of example page at
[https://surikov.github.io/webaudiofont/examples/midiplayer.html](https://surikov.github.io/webaudiofont/examples/midiplayer.html)

The example loads content of MIDI-file from binary array

```
var arrayBuffer = xmlHttpRequest.response;
var midiFile = new MIDIFile(arrayBuffer);
var song = midiFile.parseSong();
startLoad(song);
```
load array from decoded base64 string instead of xmlHttpRequest.response.

**Comment by stephaneeybert** [comment]
@sujinleeme Could you tell a bit more ? You have some source code snippet to share ? I'm fighting with this. Do I understrand I need to convert my `data:audio/midi;base64,TVRoZAAAAAYAAAABA` to an `ArrayBuffer` ?

**Comment by surikov** [comment]
@stephaneeybert don't generate text from midi-file. Load file as array.
