### ISSUE TITLE
[MIDI player Demo] How to calculate time to adjust tempo

### ISSUE THREAD

**Issue by sujinleeme** [surikov/webaudiofont#25]
Hello, @surikov.
This question is not related to webaudiofont library exactly, but I'd like to add one feature to adjust tempo(slower/faster) in MIDI player. Would you give some tips how to work on?

https://github.com/surikov/webaudiofont/blob/master/examples/midiplayer.html#L54

**Comment by surikov** [comment]
```
var stepDuration = 44 / 1000; 
```
this isn't a tempo
this is frequency of updating of queue of notes.

MIDI-file doen't store information of tempo. Every note consist of time from start of song. Change 'time' value to change speed of song.

Example https://github.com/surikov/webaudiofont/blob/master/examples/midiplayer.html#L82
```
if (track.notes[i].when >= start && track.notes[i].when < end) {
	var when = songStart + track.notes[i].when;
```

add delimiter to play faster

```
if (track.notes[i].when * 0.75 >= start && track.notes[i].when * 0.75 < end) {
	var when = songStart + track.notes[i].when * 0.75;
```
