### ISSUE TITLE
Is it possible to pass a chord to the play function?

### ISSUE THREAD

**Issue by rickdps** [surikov/webaudiofont#26]
I wondering if there is something like:

play('C');

Thank you very much.

**Comment by surikov** [comment]
Be more specific.

Define some variables if you need readable names for notes

```
var C = 0, Cs = 1, D = 2, Ds = 3, E = 4, F = 5, Fs = 6, G = 7, Gs = 8, A = 9, As = 10, B = 11;
var O = 12;
var _6th = E +O*3, _5th = A +O*3, _4th = D +O*4, _3rd = G +O*4, _2nd = B +O*4, _1st = E +O*5;
```

Use queueWaveTable to play single note. Use queueChord, queueSnap, queueStrumDown, queueStrumUp to play chords. See live example at https://surikov.github.io/webaudiofont/examples/strum.html.

Read readme of the project to learn more.
