### ISSUE TITLE
Examples not working on Chromium

### ISSUE THREAD

**Issue by ghost** [surikov/webaudiofont#27]
It seems like all examples stopped working when using Chromium on Ubuntu/GNU Linux. Most probably this is due to the Web Audio autoplay policy which was re-enabled in Chrome 71. On Firefox the examples run just fine.

**Comment by surikov** [comment]
paste here
1. exact URL of example
2. output from browser console

**Comment by ghost** [comment]
For example:
[https://surikov.github.io/webaudiofont/examples/simple.html#](https://surikov.github.io/webaudiofont/examples/simple.html#)

> WebAudioFontPlayer.js:432 WebAudioFont Player v2.80
> WebAudioFontPlayer.js:45 WebAudioFont Loader v1.27
> WebAudioFontPlayer.js:3 WebAudioFont Channel v1.04
> WebAudioFontPlayer.js:745 WebAudioFont Reverberator v1.08
> 0000_JCLive_sf2_file.js:1 load _tone_0000_JCLive_sf2_file
> simple.html:8 The Web Audio autoplay policy will be re-enabled in Chrome 71 (December 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu
>

**Comment by surikov** [comment]
this link correctly works on Windows/MacOS/IOS/Android in Chrome, Firefox, Safari, MS Edge.
This code correctly use Autoplay Policy.

I can't test it in Chromium on Ubuntu yet.

**Comment by ghost** [comment]
After having logged out and in again the problem on Chromium somehow disappeared. Deeply sorry for having wasted your time. I'll check more thoroughly before posting an issue next time.
Thank you for this wonderful software!
