### ISSUE TITLE
Examples not working on Firefox or Edge on Win10 desktop

### ISSUE THREAD

**Issue by deepbluezen** [surikov/webaudiofont#28]
Issue: No sound plays on Firefox or Edge on Win10 desktop from examples or my own project.
        
Example: Go to https://surikov.github.io/webaudiofont/examples/simple.html# in Firefox 64.0.
Console log gives:
WebAudioFont Player v2.80 WebAudioFontPlayer.js:432:1
WebAudioFont Loader v1.27 WebAudioFontPlayer.js:45:1
WebAudioFont Channel v1.04 WebAudioFontPlayer.js:3:1
WebAudioFont Reverberator v1.08 WebAudioFontPlayer.js:745:1
load _tone_0000_JCLive_sf2_file 0000_JCLive_sf2_file.js:1:1
An unknown error occurred while processing decodeAudioData.
simple.html
EncodingError: The given encoding is not supported.
An unknown error occurred while processing decodeAudioData. simple.html
EncodingError: The given encoding is not supported.
empty buffer  
Object { midi: 0, originalPitch: 5200, keyRangeLow: 51, keyRangeHigh: 55, loopStart: 87291, loopEnd: 87558, coarseTune: 0, fineTune: 0, sampleRate: 44100, ahdsr: true, … }

Known working: Desktop Win 10 Chrome, Vivaldi also Android chrome, Android Firefox

Thanks for putting webaudiofont out, it's been a great fit for stopping my current project get too bloated with audio files. Let me know if you need any further details.

**Comment by surikov** [comment]
The most of samples uses MP3/OGG compresion due big size of audio data.
Last versions of browsers includes libraries to decode MP3/OGG. 

Update your software.

Other way
use samples with SoundBlasterOld in name, for example
https://surikov.github.io/webaudiofontdata/sound/0000_SoundBlasterOld_sf2.html

Those samples use low quality SoundBlaster sounds in raw PCM without compression.

**Comment by deepbluezen** [comment]
Thanks for responding over the holiday season.

Unless you are suggesting I need to be on the nightly build channel I don't see how it can be due to older versions of the browsers?

Firefox 64.0 is the latest released build (December 11, 2018, https://www.mozilla.org/en-US/firefox/64.0/releasenotes/)

Microsoft Edge 42.17134.1.0 is the latest released build (https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/17134/?compareWith=16299)

**Comment by deepbluezen** [comment]
Managed to find another computer where it's working on those browser versions. So goodness knows why it's different on my machine. Sorry for bothering you.

**Comment by deepbluezen** [comment]
Turns out install of codecs for a VR media player had silently turned off the default built in Microsoft codecs that Edge and Firefox were expecting to find.

**Comment by surikov** [comment]
WebAudioFont relay to browser an audio decoding. You can use any samples if your browser can produce sound from MP3 or OGG. Otherwise you should use uncompressed samples only.

P.S.
sometime installing of some audio software with all audiocodecs helps.
