### ISSUE TITLE
Test are not working on iphone (Safari & chrome) on v2.59

### ISSUE THREAD

**Issue by vgordievskiy** [surikov/webaudiofont#3]

**Comment by surikov** [comment]
Not enough information. Open
https://surikov.github.io/webaudiofont/examples/drums.html
Does it work?

**Comment by vgordievskiy** [comment]
Sorry for long response.

From IPad (Safari - latest version):

[Log] WebAudioFont Player v2.59 (WebAudioFontPlayer.js, line 87)
[Log] WebAudioFont Loader v1.06 (WebAudioFontPlayer.js, line 3)
[Log] load _drum_35_17_JCLive_sf2_file (12835_17_JCLive_sf2_file.js, line 1)
[Log] load _drum_40_1_JCLive_sf2_file (12840_1_JCLive_sf2_file.js, line 1)
[Log] load _drum_42_1_JCLive_sf2_file (12842_1_JCLive_sf2_file.js, line 1)
[Log] load _drum_51_1_JCLive_sf2_file (12851_1_JCLive_sf2_file.js, line 1)
[Log] load _drum_50_1_JCLive_sf2_file (12850_1_JCLive_sf2_file.js, line 1)
[Log] load _drum_48_1_JCLive_sf2_file (12848_1_JCLive_sf2_file.js, line 1)
[Log] load _drum_41_1_JCLive_sf2_file (12841_1_JCLive_sf2_file.js, line 1)
[Log] empty buffer  (WebAudioFontPlayer.js, line 104)
Object
coarseTune: 8
file: "T2dnUwACAAAAAAAAAABjbwAAAAAAAG+2oyoBHgF2b3JiaXMAAAAAAUSsAAAAAAAAAHECAAAAAAC4AU9nZ1MAAAAAAAAAAAAAY28AAAEAAAAq2Cy7ETL////////////////////VA3Zv…"
fineTune: 5
keyRangeHigh: 51
keyRangeLow: 51
loopEnd: 0
loopStart: 0
midi: 128
originalPitch: 5900
sampleRate: 44100
sustain: 5900

**Comment by surikov** [comment]
iOS prevent from using AudioContext without user interaction.
see [https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/PlayingandSynthesizingSounds/PlayingandSynthesizingSounds.html)

**Comment by vgordievskiy** [comment]
Do you use for decode ogg vorbis? Seems safari not supported ogg((

**Comment by surikov** [comment]
Try to use instruments with 'SBLive' or 'SoundBlaster' in name. They doesn't have compression.

**Comment by surikov** [comment]
try [mixer](https://surikov.github.io/webaudiofont/examples/mixer.html)
this page doesn't use compressed sounds. The example starts init after user press Play link.

Use modern browser like Chrome for other examples.

**Comment by vgordievskiy** [comment]
I use data from old commit: c249e5a for instruments.  We develop mobile RIA(http://test2.dnotation.com).
