### ISSUE TITLE
Playing MIDI

### ISSUE THREAD

**Issue by pierre24** [surikov/webaudiofont#30]
Hi.

I have midi files stored in AWS S3 and would like to play those files on my website using webaudiofont.

I am, however, not entirely sure how to do it.

How do I need to adjust the following code in order to get it to work?

Thank you very much for your help!

_<html>
	<head>
		<script src='https://surikov.github.io/webaudiofont/npm/dist/WebAudioFontPlayer.js'></script>
		<script src='https://surikov.github.io/webaudiofontdata/sound/0250_SoundBlasterOld_sf2.js'></script>
		<script>
			var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
			var audioContext = new AudioContextFunc();
			var player=new WebAudioFontPlayer();
			player.loader.decodeAfterLoading(audioContext, '_tone_0250_SoundBlasterOld_sf2');
			function play(){
				player.queueWaveTable(audioContext, audioContext.destination
					, _tone_0250_SoundBlasterOld_sf2, 0, 12*4+7, 2);
				return false;
			}
		</script>
	</head>
	<body>
		<p><a href='javascript:play();'>Play!</a></p>
	</body>
</html>_

**Comment by surikov** [comment]
Open "MIDI player" on main project page to see how to play midi-files. Look to closed issues to see how other developers creates MIDI players.
