### ISSUE TITLE
Audio crackly on iOS 9 Safari.

### ISSUE THREAD

**Issue by defmech** [surikov/webaudiofont#31]
Hi, I'm looking at options for a midi player for a game we are developing. Unfortunately we need to support iOS 9 on iPad 2.

I've managed to get the `midiplayer.html` example working by making some small tweaks to `MIDIFile.js`, I've replaced `let` & `const` references with var, however while playback does seem to work it's a bit crackly. The sample rate seems fine at 44100 Hz. Any ideas what may be causing it? The library suits our needs almost exactly just this crackly noise problem.

**Comment by surikov** [comment]
Use https://jsbin.com/?html,output to reproduce problem
Paste linkto the code here

**Comment by defmech** [comment]
Hi, I've uploaded mode code here: https://davidlochhead.xyz/test-webaudiofont/examples/midiplayer.html#

As I said all I did was replace `let` & `const` with `var` in `MIDIFile.js` to get Safari 9 to load the demos. I've also added another simple midi file for my testing.

**Comment by surikov** [comment]
Create simple code to reproduce problem.
Example
http://jsbin.com/lamidog/1/edit?html,output

**Comment by surikov** [comment]
I can't help you without example of code, sorry.
