### ISSUE TITLE
Any tips to reduce latency?

### ISSUE THREAD

**Issue by spacejack** [surikov/webaudiofont#32]
Hi. First - fantastic project, thank you!

I am experimenting with a music player app that accepts keyboard/midi input and I have noticed there is some noticable lag between the keypress and the sound start. Maybe 100ms? It might vary from one PC to another.

At first I thought it might be the midi input but it also happens when using computer keyboard inupt.

I recall tricks in the past involving playing a silent note in the background so the audio system is already running when you play notes rather than turning it on/off frequently. Any thoughts on reducing latency?

**Comment by surikov** [comment]
This project about sound not about hardware keyboards.

Different hardware have different latency. No solution.

**Comment by spacejack** [comment]
Yes, sorry I just learned a few things about that. On Windows and Linux apparently Chrome does not have good [MIDI input latency](https://bugs.chromium.org/p/chromium/issues/detail?id=271521). It's the only browser that supports MIDI so I guess that's how it is.

And as for my typing keyboard, it's cheap and apparently cheap keyboards have terrible latency I guess I am just used to it.

Using a timer with graphics and playing notes there doesn't appear to be any audio lag. Maybe I'll try a Mac or look at getting input over a socket somehow.
