### ISSUE TITLE
in function player.findEnvelope, envelope.when and envelope.duration is always undefined if it is newly created.

### ISSUE THREAD

**Issue by yw662** [surikov/webaudiofont#36]
https://github.com/surikov/webaudiofont/blob/6aa83c160256f542310fb9b9c4676ac4ada4dd52/npm/src/player.js#L203-L216

suggested fix:

```js
envelope = audioContext.createGain();
envelope.target = target;
envelope.when = when;
envelope.duration = duration;
envelope.connect(target);
```

**Comment by surikov** [comment]
see definition here
https://github.com/surikov/webaudiofont/blob/6aa83c160256f542310fb9b9c4676ac4ada4dd52/npm/src/player.js#L115

**Comment by yw662** [comment]
So does it mean, `findEnvelope` should not be directly called from outside ?

**Comment by surikov** [comment]
It means envelope is a cached GainNode for a played sound. Player can destroy or reuse any envelope in any time.
