### ISSUE TITLE
Hello, I have created a typescript fork version of this project

### ISSUE THREAD

**Issue by yw662** [surikov/webaudiofont#37]
https://github.com/yw662/webaudiofont-ts

I think I should tell you about this. Maybe issues is not a good place, it is the best place I can find :-).

**Comment by surikov** [comment]
Hi
Looks nice

**Comment by surikov** [comment]
I added link to the project into readme.md

**Comment by stephaneeybert** [comment]
@yw662  You would have an example usage of your fork ?
