### ISSUE TITLE
suggestion: loader: load fonts with fetch/xhr instead of script tag

### ISSUE THREAD

**Issue by yw662** [surikov/webaudiofont#38]
https://github.com/surikov/webaudiofont/blob/6aa83c160256f542310fb9b9c4676ac4ada4dd52/npm/src/loader.js#L20-L24

Maybe it is better to load audio fonts with fetch or xhr, instead of load them in script tag.
Loader can also avoid setting global variables like `window[name]` in this way.
It may require changes on all audio fonts, though.

**Comment by surikov** [comment]
Browser doesn't allow read data from different domain. Look to

https://medium.com/netscape/hacking-it-out-when-cors-wont-let-you-be-great-35f6206cc646

Script tag is only way to use sounds directly from github.io without uploading whole huge WebAudioData to your own site.

**Comment by yw662** [comment]
github.io set CORS headers. I tested it on my own website and it works.

```js
const xhr = new XMLHttpRequest();
xhr.onreadystatechange=()=>console.log(xhr.response);
xhr.open('GET', 'https://surikov.github.io/webaudiofontdata/sound/0290_Aspirin_sf2_file.js');
xhr.send();
```

It works.

and resp header looks like this:

```
accept-ranges: bytes
access-control-allow-origin: *
age: 0
cache-control: max-age=600
content-encoding: gzip
content-length: 144997
content-type: application/javascript; charset=utf-8
date: Tue, 23 Jul 2019 07:18:30 GMT
etag: W/"5c81214c-31078"
expires: Tue, 23 Jul 2019 07:28:30 GMT
last-modified: Thu, 07 Mar 2019 13:49:00 GMT
server: GitHub.com
status: 200
vary: Accept-Encoding
via: 1.1 varnish
x-cache: MISS
x-cache-hits: 0
x-fastly-request-id: 5b91a771ddee30cebce84bc657a7421bf9b45b05
x-github-request-id: C12C:5382:18D55:20956:5D36B4C3
x-proxy-cache: MISS
x-served-by: cache-ewr18130-EWR
x-timer: S1563866310.437644,VS0,VE31
```

and you can see: `access-control-allow-origin: *`.

BTW we can get rid of `setTimeout(..., 333)` and `window[name]` by using fetch or xhr. They only problem is that the response is js code. It needs some extra process.

**Comment by surikov** [comment]
May be it works now. 
Script tag avoid CORS problem at all.
