### ISSUE TITLE
queueWaveTable with offset

### ISSUE THREAD

**Issue by vitto32** [surikov/webaudiofont#40]
Is it possible to play a portion of a waveTable?

Using `envelop.audioBufferSourceNode.stop(T)` I can (ugly) trim it from 0 to T, where 0 < T < duration.
What I should do to play just from T to duration? I need the sound "tail".
Something like the 2nd parameter of `AudioBufferSourceNode.start`.

**Comment by surikov** [comment]
player.queueWaveTable has 'when' and 'duration' parameters.

**Comment by vitto32** [comment]
I know. But there is no ‘offset’ parameter. I can only play a full waveTable, non just a portion.

**Comment by surikov** [comment]
Why do you need this?

**Comment by vitto32** [comment]
I do have a midi player and I’m replacing the previous soundfont with this (amazing) library. But without the offset param, I can only seek with note “snapping”.

**Comment by surikov** [comment]
I do not understand what is 'I can only seek with note “snapping”' and why do you need this.

Look to example of MIDI-player. Listen to embedded files or upload your own file. It works fine.

**Comment by vitto32** [comment]
In my case (an edu app) the midi's are much more simple and in some cases with just a couple of instruments and long notes.

If a note is played from time 0:00 to 0:05 and I seek to 0:03, I have 3 options: 
1. ignore that note (and eventually play the other notes that starts after 0:03)
2. play a shorter note
3. force the song time to 0:00 or 0:05 (snapping the seek bar to the note start / end)

Solution 1 is how the MIDI-player example works (if I've understood it right). It's fine for "fast" midi's with lot of instruments but in my case the missing note is noticeable and ruins the educational purpose.

Solution 2 is perfect only if I can play the "tail" of that note (using an offset parameter). Playing it as a shorter note (when 0:03, duration 2") produces a musically wrong output.

Solution 3 is my fallback solution. I do search the nearest position where no notes by any instruments are played and play from there. In some situations this means I can not seek at all (bad) but at least I always produce a correct output.

**Comment by surikov** [comment]
The most of musical software uses option 1.
Option 3 is too hard to implement in right way.

**Comment by vitto32** [comment]
I'm working on option 3 (just for basic usage) and it seems not so hard. 
But I'm probably totally wrong about this.

I've added an `offset` parameter to `queueWaveTable` and use it like this: 
`envelope.audioBufferSourceNode.start(startWhen, zone.delay + (offset || 0));`
(in my test case I've seen that zone.delay is always 0, I don't know what would happen if it is not).

This seems to work in terms of buffer content. 

Now I'm looking in the `setupEnvelope` part to adjust the volume accordingly, at least when `ahdsr === true`. I'll probably have to interpolate the volume at offset and change the ahdsr accordingly.
