### ISSUE TITLE
static utilities

### ISSUE THREAD

**Issue by ritz078** [surikov/webaudiofont#41]
There are multiple functions that can be implemented as static functions like `findInstrument, instrumentNames` etc. There are many more like this. currently, I have to create an instance every time I have to use those utilities anywhere in the app.

**Comment by surikov** [comment]
Please be more specific.

**Comment by ritz078** [comment]
currently to get info of a track I have to do

```js
const player = new WebAudioFontPlayer();
const nn = player.loader.findInstrument(song.tracks[0].program);
const info = player.loader.instrumentInfo(nn)
```

Now if I have the `program` number and want to just know the track info, I can't do it without creating a new instance of WebAudioFontPlayer even though they can totally be separate utilities.

The API can be something like

```js
import WebAudioFontPlayer, { findInstrument, instrumentInfo } from "webaudiofont";

const info = instrumentInfo(findInstrument(62))
```

**Comment by surikov** [comment]
instrumentInfo is a URL of instrument's data at WebAudioFontData store. This link meaningless without WebAudioFont loader.

See https://en.wikipedia.org/wiki/General_MIDI for list of all names for MIDI instruments and percussion.
