### ISSUE TITLE
Dynamic loading

### ISSUE THREAD

**Issue by JohnAllen69** [surikov/webaudiofont#43]
When I use Dynamic loading, i set a val for the notes, The notes play great. 
I have a button to play a sound sample. 
However when i invoke the Dynamic loading and try to change instruments. the current instrument will continue to play everytime i hit the Play button until i change the notes varible to a new sound. 
then the change of instrument takes affect.
my play button calls the start() function, so the start() function continues to play the same instrument, until a change occurs to the beats.

is there a way to make the instrument change right away so that when i start() again the same notes will play with the  new instrument. 

var instr=null;
var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
var audioContext = new AudioContextFunc();
var player=new WebAudioFontPlayer();
function changeInstrument(path,name){
	player.loader.startLoad(audioContext, path, name);
	player.loader.waitLoad(function () {
		instr=window[name];
	});
}
changeInstrument('https://surikov.github.io/webaudiofontdata/sound/0290_Aspirin_sf2_file.js','_tone_0290_Aspirin_sf2_file');

**Comment by surikov** [comment]
Player plays new instrument right after you load it.
Check you code.

Copypaste here your code for your start function so i can fix it.

**Comment by JohnAllen69** [comment]
Thank you, It was my mistake. I was using an eval with the notes before they were passed into the nextPiece()  function. I know eval is evil but I could not figure a way around it. So I changed my eval location to the following code. If you have any suggestion as to doing away with eval, it would be much appreciated.  I am using C# to generate the notes variable and then passing it back into a getSound function and the eval was initially placed in this function before the start() function was ever called. thus causing my issue. As always, thank you so much for your assistance.

function nextPiece() {
            var run = eval(notes)
            for (var n = 0; n < run.length; n++) {
                var beat = run[n];
                for (var i = 0; i < beat.length; i++) {
                  
                    if (beat[i]) {                      
                         player.queueWaveTable(audioContext, audioContext.destination, beat[i].preset, startTime + n * beatLen, beat[i].pitch, beat[i].duration, beat[i].volume);
                    }
                }
            }
            end;
        }

**Comment by surikov** [comment]
Use array with notes. 
Send notes to queue. 
See examples at project page.

Please be more specific if you need a help.
