### ISSUE TITLE
I made this little website using your library. One question.

### ISSUE THREAD

**Issue by Jonathhhan** [surikov/webaudiofont#44]
Hi, my approach is very similar to the midi keyboard / dynamig loading example but with midi in / out selection.
thanks for your work, nice library.
https://webmidi.handmadeproductions.de/

A question: How can I play drums like gm MIDI, so that each pitch plays a different drum instrument? 
Like loading this drum sound bank at once: https://surikov.github.io/webaudiofontdata/sound/drums_0_FluidR3_GM_sf2_fileStandard.html
Or do I need to load every sound seperately or change it with the pitch?
I think I need to find out how the MIDI player example works, because it seems to play every intended drum sound and does also find the right instruments.

And another Question: Is there a way to select the 128 sounds of a soundbank, and perhaps to switch the bank seperately (like it is done with gm MIDI too)? Then it would be possible to select the instrument with MIDI program change.

**Comment by surikov** [comment]
For drums you need to load every drum as separate instrument.

You don't need to load whole bank. You can load selected instruments and drums only.

Keep in mind, some instrumens has huge size about 3-5mb.

**Comment by Jonathhhan** [comment]
Thanks, i think i found a good solution for what i wanted to try. I edited WebAudioFontPlayer.js so that i have only the 128 gm MIDI sounds and the standard drum sounds. This way I can change the sound with MIDI and program change and play with drum sequencers the sounds from the site.
here is the updated result: https://webmidi.handmadeproductions.de
Do you know if it is possible to open several web 
MIDI ports at at time?
I also tried to understand the effect thing (the reverberator). If I understand it right I have to create channels for every sound, connect them to a master channel, and connect the master channel to the reverb?
[WebMIDIFont.zip](https://github.com/surikov/webaudiofont/files/3668493/WebMIDIFont.zip)

**Comment by surikov** [comment]
Open
https://github.com/surikov/webaudiofont#code-examples

There are examples for drums, reverberator, MIDI-keyboard
