### ISSUE TITLE
Is midi effects like Volume Control, PitchBend and Panning supported?

### ISSUE THREAD

**Issue by aamironline** [surikov/webaudiofont#47]
**Is your feature request related to a problem? Please describe.**
We are building a web-based DAW kind of application. We like your library. However, the example you have developed does not showcase effects like pitch band, panning, and message-based volume control. Is this library supports that? If not, do you have plan to support anytime sooner?

**Comment by surikov** [comment]
You misunderstand what MIDI is.

> MIDI (/ˈmɪdi/; short for Musical Instrument Digital Interface) is a technical standard that describes a communications protocol, digital interface, and electrical connectors that connect a wide variety of electronic musical instruments, computers, and related audio devices

see https://en.wikipedia.org/wiki/MIDI

See 'Example applications' at main page of WebAudioFont project. 
It shows all features for musical applications.

**Comment by aamironline** [comment]
Yes, I am aware of what MIDI is. All I want to know the way we can send pitch-bend and other control messages in MIDI, can we produce the same effect with this library?

**Comment by surikov** [comment]
Try to understand - no one audio library support MIDI messages because MIDI is protocol. MIDI isn't audio.

See 'Example applications' at main page of WebAudioFont project. Some of apps are sequencers that uses pitch bends for audio, reading/writing MIDI files, etc.
All of them uses WebAudioFont to produce sound.

**Comment by aamironline** [comment]
I'm not saying whether this library can be used for sending MIDI messages or not. All I intend to know can we produce effects like Pitch Bend with this framework. 

> Some of the apps are sequencers that use pitch bends for audio

This answers my query. I would request to have a dedicated example in this context.

Thanks :)
