### ISSUE TITLE
Add tonejs support

### ISSUE THREAD

**Issue by etamity** [surikov/webaudiofont#48]
I have been searching Tonejs implement for this project, only find a year ago you have been trying to implement here https://github.com/Tonejs/Tone.js/issues/290 , wondering is there any progress?

Thank you for your awesome work!

**Comment by surikov** [comment]
WebAudioFont is a full-fledged engine that uses realistic musical instruments.
You can use it to create apps like this https://www.youtube.com/watch?v=vJc11SsyfQ4

Tone.js is a library to play sound filres and effects. Tone.js doesn't have library with musical instruments.

WebAudioFont  doesn't need Tone.js.

**Comment by stephaneeybert** [comment]
but Tone.js need WebAudioFont :-)
