### ISSUE TITLE
Add a ready boolean variable to the player

### ISSUE THREAD

**Issue by b2renger** [surikov/webaudiofont#5]
I'm looking for a way to disable the interaction while loading a soundfont until the loading and decoding is finished.

I looked at the dynamic loading example, and tried to implement the change function with no success.I thought the player.loader.waitLoad() was to be used as a callback but I can't seem to make it work. I also looked at the player.loader.progress() function but it always returns 1. I guess those are used when you download from the webfontaudiodata repo.

Is there a flag / variable / function that I can use to know when the player is ready to play ?

**Comment by surikov** [comment]
see [https://surikov.github.io/webaudiofont/test.html](https://surikov.github.io/webaudiofont/test.html)

>			var player = new WebAudioFontPlayer();
>			var c = new AudioContext();
>			player.loader.startLoad(c, 'https://surikov.github.io/webaudiofontdata/sound/0000_Chaos_sf2_file.js', '_tone_0000_Chaos_sf2_file');
>			player.loader.waitLoad(function () {
>				console.log('done');
>			});

**Comment by b2renger** [comment]
@surikov it doesn't work for my use case.

I'm doing pretty much the same thing : https://github.com/b2renger/p5js_harmony-directed-layout/blob/master/sketch.js#L31

soundfonts are into tables : https://github.com/b2renger/p5js_harmony-directed-layout/blob/master/soundtable.js

I'm also trying to change the soundfont with a dropdown menu from quicksettings : https://github.com/b2renger/p5js_harmony-directed-layout/blob/master/sketch.js#L176-L185

It doesn't look like the waitLoad function is called at all.

**Comment by surikov** [comment]
open test page [https://surikov.github.io/webaudiofont/test.html](https://surikov.github.io/webaudiofont/test.html) 

Look to browser console. Listen the sound. It works.

Please be more specific. Post URL that anybody can run in browser and look to result.

**Comment by b2renger** [comment]
I know it works in your case, but I fail to adapt it to a dynamic loading with a way to alert the user that the player is not ready to use (while it is still loading and decoding).

the url is here : 
https://b2renger.github.io/p5js_harmony-directed-layout/

as for being more specific I want to be able to select a soundfont from a dropdown menu, I want to be able to store references to the soundfonts in tables, and I want to be able to do all this offline.

on the url : you need to double click on the sound parameters menu to be able to use the dropdown menus.

**Comment by surikov** [comment]
i fixed code. Replace your files with fixed version. Use diff to see what to change.


[fixedfiles.zip](https://github.com/surikov/webaudiofont/files/981831/fixedfiles.zip)

**Comment by b2renger** [comment]
It works like charm ! thanks a lot @surikov 
and thanks again for the lib !
