### ISSUE TITLE
Unable to play sounds on iOS

### ISSUE THREAD

**Issue by samuelbradshaw** [surikov/webaudiofont#50]
**Describe the bug**
I'm using webaudiofont on my website to generate audio as a "pitch pipe". When a user presses the "pitch pipe" button, it plays four notes consecutively: The first note of the bass, tenor, alto, and soprano parts of a song. This works on Safari, Chrome, and Firefox on macOS, but doesn't work on Safari on iOS.

**To Reproduce**
1. On an iOS device, go to a page with a pitch pipe button: https://singpraises.net/collections/en/hymns/the-morning-breaks/presentation-lyrics?audiotype=pp
2. Tap where it says "Pitch pipe ▶".

**Expected behavior**
Audio should play four consecutive notes.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.3
 - Browser: Safari
 - Version: (13.3)

**Additional context**
This is my first time using webaudiofont, so it's possible I'm doing something wrong – however, my setup is simple and it seems to work on other platforms (just not on iOS).

The pitch pipe button has an `onclick` attribute, which calls `playPitchPipe(['C3', 'C4', 'E4', 'G4']);`:
```
<button id="options-button" class="icon-button" onclick="playPitchPipe(['C3', 'C4', 'E4', 'G4']);">Pitch pipe <i class="fa fa-play-circle"></i></button>
```

I'm loading webaudiofont and a sound font like this:
```
      <script src="https://surikov.github.io/webaudiofont/npm/dist/WebAudioFontPlayer.js"></script>
      <script src="https://surikov.github.io/webaudiofontdata/sound/0000_Chaos_sf2_file.js"></script>
```

And this is my JavaScript:
```
      var AudioContextFunc = window.AudioContext || window.webkitAudioContext;
      var audioContext = new AudioContextFunc();
      var player = new WebAudioFontPlayer();
      player.loader.decodeAfterLoading(audioContext, '_tone_0000_Chaos_sf2_file');
      function playPitchPipe(pitches) {
        for (var p = 0; p < pitches.length; p++) {
          player.queueWaveTable(audioContext, audioContext.destination, _tone_0000_Chaos_sf2_file, audioContext.currentTime + (0.75 * p), convertToMidi(pitches[p]), 2);
        }
      }
```

**Comment by surikov** [comment]
Look to borowser console. It sjow warning

> presentation-lyrics?audiotype=pp:726 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

You need to start AudioContext from a UI event like button clicks. Otherwise some browser will block audio.

Yse waitLoad function to make sure downloading of samples finished. See https://github.com/surikov/webaudiofont/wiki/4.3.-waitLoad

**Comment by surikov** [comment]
just in case

iPhone has trigger at the side. Try to switch it. This trigger mutes speaker for Web Audio API sounds but other sounds (audio from Youtube for example) works despite the trigger state. Also Web Audio still plays via earphones.

This is very strange behaviour of iPhone.

**Comment by samuelbradshaw** [comment]
Thanks! I tried toggling the mute switch, and adjusting the volume, but it didn't help. Maybe it's an iOS bug?

**Comment by samuelbradshaw** [comment]
Thanks! I thought I had tried it before, but toggling the mute switch worked now! It must be an iOS bug.
