### ISSUE TITLE
Converting to webaudiofont from another library

### ISSUE THREAD

**Issue by bbevren** [surikov/webaudiofont#52]
Hi, i am using midi-js and want to convert it to webaudiofont...
is there easy way to immigrate? Midi-js has chords like this { "C:maj": [ 60, 64, 67 ], "C:min": [ 60, 63, 67 ], "C:dim": [ 60, 63, 66 ], "C:maj7": [ 60, 64, 67, 71 ], "C:min7": [ 60, 63, 67, 70 ]
while webaudiofont has 
var fretsAm = [-1, 0, 2, 2, 1, 0];
			var fretsC =  [-1, 3, 2, 0, 1, 0];
			var fretsE =  [ 0, 2, 2, 1, 0, 0];
			var fretsG =  [ 3, 2, 0, 0, 0, 3];
			var fretsDm = [-1,-1, 0, 2, 3, 1];

Thanks

**Comment by surikov** [comment]
send notes one by one via queueWaveTable or use queueChord.
read description here https://github.com/surikov/webaudiofont/wiki
listen to examples here https://surikov.github.io/webaudiofont/examples/strum.html
