### ISSUE TITLE
How do you change the volume of a Tone.WebAudioFontInstrument node?

### ISSUE THREAD

**Issue by lakefox** [surikov/webaudiofont#53]
Hi I'm using this code

``` javascript
synth = new Tone.WebAudioFontInstrument({
  			"oscillator" : {
  				"type" : "sine"
  			},
  			"envelope" : {
  				"attack" : 0.01,
  				"decay" : 0.2,
  				"sustain" : 0.2,
  				"release" : 0.2,
  			}
  		}).toMaster();
```

and I can't figure out how to change the volume. I've tried everything on the tone js website and nothing works.

**Comment by surikov** [comment]
Dpn't use Tone.js
Look to https://github.com/surikov/webaudiofont#code-examples
Example about volumes https://surikov.github.io/webaudiofont/examples/mixer.html
