### ISSUE TITLE
How to change playing speed, include pause and loop ?

### ISSUE THREAD

**Issue by ghost** [surikov/webaudiofont#54]
I would like to use MIDI player for our small chorale. The main idea is to give possibilities to do repetitions and learning at home for all people. That is why I need to add some modifications to [midi player](https://surikov.github.io/webaudiofont/examples/midiplayer.html#) as  speed adjustment to sing some parts very slowly.  Thanks for your help.

**Comment by surikov** [comment]
What do You need exactly?Do You need help in learning Javascript?

Look to examples, ask other users.

**Comment by ghost** [comment]
Hi Using bld222's solution pausing is working well.
