### ISSUE TITLE
Two licensing questions

### ISSUE THREAD

**Issue by ponpondev** [surikov/webaudiofont#57]
Hi,
I have two questions about the project's licensing:
1. **I see that it used to be under MIT, now it's GPLv3. Why is it?** MIT surely provides the flexibility to use the library without having to worry about licensing like GPLv3. It also makes source code disclosure NOT a must when being added to a distributable project as plug-in.
2. **What license are YOUR Javascript soundfonts under?** I hope it's the same as GeneralUserGS's and FluidR3's so I could sublicense it in my software.

**Comment by surikov** [comment]
License is GPLv3 now.

**Comment by mk-pmb** [comment]
I had to research it myself today, so for anyone interested: The license seems to have changed on 2020-01-16. The relevant commits from that day seem to be [these](https://github.com/surikov/webaudiofont/compare/c320782853925a11acf9c4881f6a309b2cdeeb74...934a7eb3d4c82ccae4ed93431c76bf3d08bebc7f).
