### ISSUE TITLE
Bugs in GeneralUserGS and FluidR3 WebAudioFont presets

### ISSUE THREAD

**Issue by notator** [surikov/webaudiofont#58]
Many thanks for all the work that has gone into this great project! :-)

I've been using clones of some of the GeneralUserGS and FluidR3 preset files in my own ResidentWAFSynth project, and have found some bugs:

The following zones are redundant (other zones cover the same ranges):

GeneralUserGS preset 0 (Grand Piano)
- keyRangeLow=88, keyRangeHigh= 90
- keyRangeLow=61, keyRangeHigh=61

GeneralUserGS preset 10 (Music Box)
- keyRangeLow=0, keyRangeHigh= 80
- keyRangeLow=81, keyRangeHigh=113

FluidR3 preset 89 (Pad2)
- keyRangeLow=0, keyRangeHigh= 108

FluidR3 preset 93 (Pad6)
- keyRangeLow=0, keyRangeHigh= 108

FluidR3 preset 92 (Pad5) has 3 zones that all start at keyRangeLow=0. (My solution was to remove the middle one and make the other two contiguous.)

I've only checked the preset files listed in the residentWAFSynth/webAudioFontFiles folder in my [repository](https://github.com/notator/ResidentWAFSynthHost). Perhaps someone has time to do a more systematic check?

All the best,
James

**Comment by surikov** [comment]
There 2000 instruments and drums in the library. Some of them have bugs.
This is free project. You need to check instruments by yourself.

**Comment by notator** [comment]
Yes, agreed. There's no guarantee that even official soundFonts are bug free.
Its probably best to check the instruments for contiguity and correct them as necessary _when loading them into a project_ (as I am doing).
Each instrument zone should start with keyRangeLow equal to 1 + the previous zone's keyRangeHigh. The first zone need not have keyRangeLow equal to 0, and the last zone need not have keyRangeHigh equal to 127.
