### ISSUE TITLE
Extract the names of tracks from a midi file

### ISSUE THREAD

**Issue by n-ice-ch** [surikov/webaudiofont#59]
Some midi files contains track names. It would be very helpful to be able to display them in the player.
I saw some information like **MIDIEvents.EVENT_META_TRACK_NAME** but I'm not able to handle it right to show the track name.

**Comment by surikov** [comment]
WebAudioFont is a library of musical instruments not MIDI-player.
Page with MIDI-player is a small example to demonstrate benefits of the library. 

Write your own MIDI-player if you need it.
