### ISSUE TITLE
Mac Problem

### ISSUE THREAD

**Issue by mrdev023** [surikov/webaudiofont#6]
![18405456_1672530476386044_203718608_o](https://cloud.githubusercontent.com/assets/11292703/26296332/c3fe99d2-3ebd-11e7-9551-6c9ef6392105.png)

**Comment by surikov** [comment]
please add full details to reproduce the problem

**Comment by mrdev023** [comment]
This bug appears only on OsX, when i try to play (noteOn). ->

```
noteOn(midiNote) {
			var noteModifiee = midiNote+parseInt(this.modifTonale.transposition)+parseInt(this.modifTonale.modulationEffective)+parseInt(this.modifTonale.incrementationEffective);
            if (this.notes_state[noteModifiee] >= 1){
				this.noteOff(midiNote);
            }
            this.findNote(noteModifiee).envelope = this.player.queueWaveTable(this.audioContext, this.audioContext.destination, this.selectedPreset, 0, noteModifiee, 999, (window.velocity*this.volumePiste) * 0.5);
            this.notes_state[noteModifiee] += 1;
        }
```

you can see an empty buffer when i try to stop with noteOff.

And to load intruments, i'm used this function:

```
setPreset(preset){
            var _this = this;
            this.player.loader.startLoad(this.audioContext, this.listeInstruments[preset]["url"], _this.listeInstruments[preset]["object"]);
            this.player.loader.waitOrFinish(_this.listeInstruments[preset]["object"],function(){
                console.log(_this.listeInstruments[preset]["object"] + " load done");
                _this.selectedPreset = window[_this.listeInstruments[preset]["object"]];
                _this.selectedPresetString = preset;
            });
        }
```

with preset = the index of array of Object ({url:"Url of javascript instrument",object:"the global name in the javascript file"})

**Comment by surikov** [comment]
Safari can't decode OGG but the most of instruments used OGG.

Solution:
1. Try to use instruments with 'SBLive' or 'SoundBlaster' in name. They doesn't have compression. 
Test https://surikov.github.io/webaudiofont/examples/mixer.html in Safari. It works.
2. Use modern browser like Chrome.
