### ISSUE TITLE
midi player issues

### ISSUE THREAD

**Issue by gultekinmg** [surikov/webaudiofont#61]
**window.requestAnimationFrame(function (t) {tick(song, stepDuration);});**
causes cumulation on sendnotes when switching on tabs or other browser activity. not a good
selection for audio. **interval** animation was better.
and.
i have classified instrument soundfonts joining them in bigger file such as 'JsLive.js' that works fine
for manual instrument playing. but in midi playing waf.js redirects to github.io in complex setting.
not enabling us choose a different soundfont. whole bunch of selection inputs causes stalls also.
how i could select a GSLive set?

**Comment by surikov** [comment]
MIDI-player is a simple example. Chrome want to freeze activities for any background tab. My example of MIDI-player obeys the rules. You need to create your own player if you need more functions.

Look to example 'dynamic loading' at project description to learn more about instrument selection.

There aren't a file waf.js in this project. 

Please create separate issue for each question.
