### ISSUE TITLE
Avoid Runtime Error when using OfflineAudioContext

### ISSUE THREAD

**Issue by dannybullo** [surikov/webaudiofont#63]
Hi! The first line of code of **queueWaveTable()** is

**if (audioContext.state == 'suspended') {
     console.log('audioContext.resume');
    audioContext.resume();
}**

This works fine. However, there are cases where it is desired to use an **OfflineAudioContext**, such as Rendering/Exporting to a WAV file. I managed it to work fine. However, the following error is thrown:

**Uncaught (in promise) DOMException: cannot resume an offline context that has not started**

This is expected, as we should not use **resume() ** in an **OfflineAudioContext**. A simple solution would be:

**if (audioContext.state == 'suspended' && audioContext.constructor.name == "AudioContext") {
                console.log('audioContext.resume');
                audioContext.resume();
}**

What do you think?

Thanks!
Danny Bullo

**Comment by surikov** [comment]
fixed

**Comment by dannybullo** [comment]
Thanks @surikov
