### ISSUE TITLE
Playing multiple notes 

### ISSUE THREAD

**Issue by mohammadalmalt** [surikov/webaudiofont#64]
Hello, 

I would like to know how can i play 2 or more notes after each other. When I do the following, the notes are played together:
player.queueWaveTable(audioContext, audioContext.destination  , instr, 0, 12 * 5+ 0, 1);
player.queueWaveTable(audioContext, audioContext.destination  , instr, 0, 12 * 5+ 4, 1);

Also, how can I make the playing continue while I am pressing a button and stops when i release the button? 

Many thanks for your great code, I really enjoyed it.

**Comment by surikov** [comment]
Look to examples https://github.com/surikov/webaudiofont#code-examples
Read docs https://github.com/surikov/webaudiofont/wiki
Ask one question per issue. 
Add full code to issue if you need to fix it.
