### ISSUE TITLE
SFZ format support

### ISSUE THREAD

**Issue by Catsvilles** [surikov/webaudiofont#67]
Hi, just getting into soundfonts, so it may be I don't fully understand something, sorry.
WebAudioFont is cool and has already many things I would use but I'm aiming towards more high quality music production and found many SFZ soundfont high quality audio libraries and I'm interested if it would be possible to use SFZ soundfont with this library? Thank you!

**Comment by surikov** [comment]
SZF is a compressed version of SF2.
SF2 is a library of instrument.
Some of soundfont consists with high quality instruments, some consists of low quality instruments.
WebAudioFont uses big library composed from many soundfonts. See catalog.
