### ISSUE TITLE
Pause implementation

### ISSUE THREAD

**Issue by sdoherty0** [surikov/webaudiofont#68]
**Is your feature request related to a problem? Please describe.**
Do you have any MIDI player that implements a pause feature and uses Web Audio API? I know it is pretty complex with scheduling notes and using the tick method to play them. I have based my work on yours and I know you know this software very well, but I haven't found a pause feature in any of your examples.

**Describe the solution you'd like**
A working pause feature for the Web Audio API playing MIDI files.

**Comment by surikov** [comment]
A MIDI player is a small example.
Maybe I'll post more complex examples later.
No free time yet.
