### ISSUE TITLE
No Example for ES6 Imports

### ISSUE THREAD

**Issue by frastlin** [surikov/webaudiofont#69]
Hello,
There is no example that I can find that uses ES6 imports. The nearest thing I can find is the "Minimal NPM code (if you need this)", but that uses Node syntax.
I'm having problems finding the presets. Here is what I have:

	import WebAudioFont from 'webaudiofont'
	
	const AudioContextFunc = window.AudioContext || window.webkitAudioContext
	const audioContext = new AudioContextFunc()
	const player = new WebAudioFont()
	player.loader.decodeAfterLoading(audioContext, '_tone_0250_SoundBlasterOld_sf2')
	function play(){
		player.queueWaveTable(audioContext, audioContext.destination,
			window._tone_0250_SoundBlasterOld_sf2, 0, 12*4+7, 2)
	}

I also tried importing the preset by doing:

	import WebAudioFont, { _tone_0250_SoundBlasterOld_sf2} from 'webaudiofont'

I looked at player:

	player._tone_0250_SoundBlasterOld_sf2

and what is returned by:

	const _tone_0250_SoundBlasterOld_sf2 = player.loader.decodeAfterLoading(audioContext, '_tone_0250_SoundBlasterOld_sf2')

I'm not sure what else to try.

**Comment by surikov** [comment]
see https://github.com/surikov/webaudiofont#dynamic-loading

**Comment by MrThanlon** [comment]
Hi, check this out https://www.npmjs.com/package/@mrthanlon/webaudiofont
