### ISSUE TITLE
is it possible to play more than one note at the same time?

### ISSUE THREAD

**Issue by seant-ca** [surikov/webaudiofont#7]
Hi there,

Is it possible to play more than one note at the same exact time? Like in a chord? It doesn't seem to work? Is this not possible using Audio Context? Do you need a new AudioContext in order to do this?

If it is possible, please provide a code example that demonstrates how to do this.

Thanks.

**Comment by surikov** [comment]
Yes, you can. Look to example https://surikov.github.io/webaudiofont/examples/realtime.html

How it works
read documentation at https://github.com/surikov/webaudiofont
open catalog of sounds at https://surikov.github.io/webaudiofontdata/sound/
choose a sound, for example https://surikov.github.io/webaudiofontdata/sound/0190_JCLive_sf2_file.html
press links  in [chords: Am | C | E | G] to listen a chord
right-click page and select 'View page source' to view code

look to Code examples section at https://github.com/surikov/webaudiofont to learn how to define timing etc.
