### ISSUE TITLE
Is there an envelope.cancel function equivalent for queueChord

### ISSUE THREAD

**Issue by jepcolombia** [surikov/webaudiofont#73]
Iam using queueChord but could not figure it out how to stop playing the chord notes. Is there any function or instruction to do that?  queueWaveTable has envelope.cancel function, but this does not work with queueChord.

best Regards
Jairo

**Comment by surikov** [comment]
Hi
Now queueChord returns array of envelopes.
See browser's console output
https://surikov.github.io/webaudiofont/examples/strum.html
