### ISSUE TITLE
Annoying sound even when using the same example with other data

### ISSUE THREAD

**Issue by amalthakir** [surikov/webaudiofont#75]
*Describe the bug*
Annoying sound when running the code

*To Reproduce*
1. pressing on start

*Expected behavior*
I am trying to build music that receives the notes information from the API and plays it using the code mentioned in the example on the following link.

https://surikov.github.io/webaudiofont/examples/realtime.html

When I reduce the number of sent notes the problem disappears, but when the charge of my device is low, even if it is a few notes, noise and noise come out.

*Screenshots*
I will attach a video

*Desktop (please complete the following information):*
 - Browser [chrome] Version [96.0.4664.4

*Additional context*
I will attach the code and the data sent from the API you can run the code directly and hear the problem, Please change the file extension to HTML

[code.txt](https://github.com/surikov/webaudiofont/files/7569122/code.txt)

https://user-images.githubusercontent.com/59692667/142597394-5d266d5f-d73f-4355-a656-0f5f53f77929.mp4

**Comment by surikov** [comment]
Please don't double same issue. Look to https://github.com/surikov/webaudiofont/issues/74
