### ISSUE TITLE
How to use the envelope as returned from player.queueWave...

### ISSUE THREAD

**Issue by wrcstewart** [surikov/webaudiofont#77]
I 'm not sure how to use this ..could you help with a couple of lines of code?

For example I tried:

var env = player.queueWaveTable
           (audioContext, audioContext.destination, _drum_47_0_Chaos_sf2_file, 0  ,58, 1.0);

          var bsn = env.audioBufferSourceNode;

          bsn.loop = true; 

This only sounds one drum beat and doesn't loop. I tried various combination with loopStart, loopEnd and start but nothing gave me a loop.

Thanks in advance if you can spare the time.

**Comment by surikov** [comment]
check out this example
https://surikov.github.io/webaudiofont/examples/realtime.html

Look to the source of the example.
