### ISSUE TITLE
adding  new sound fonts

### ISSUE THREAD

**Issue by AkMusic197** [surikov/webaudiofont#78]
**Is your feature request related to a problem? Please describe.**
need to update the library with my new sound fonts

**Describe the solution you'd like**
adding sound fonts with these extensions .sf2    .exs  .nki   .sfz.

**Describe alternatives you've considered**
music produced on this 

**Additional context**

**Comment by surikov** [comment]
Look to answer at
https://github.com/surikov/webaudiofont/issues/14

**Comment by AkMusic197** [comment]
@surikov its not a solution I've tried it before

may I send you my sound fonts and you add it ?

**Comment by surikov** [comment]
This is worked solution. See tutorial. Listen to sound of instrument from Kontakt library.

**Comment by AkMusic197** [comment]
Listen to sound of instrument from Kontakt library. am I able to use Kontakt library ???

**Comment by AkMusic197** [comment]
the video tutorial is not available

**Comment by surikov** [comment]
The tutorial is text, not video. Read the tutorial.
I converted all 2000 instruments and drums from different .sf2 files in same way.

The video in this tutorial is a demo of the original Kontakt instrument sound.
I think the owner of original Kontakt instrument deleted the video.

**Comment by AkMusic197** [comment]
kontakt soundfonts extention is .nki not SF2 can I convert it the same way ?

**Comment by surikov** [comment]
Extract audio from any library and convert it the same way.

I think this is too hard work.
Moreover, your library license prohibits such use.

Use 2000 existing instruments and drums.
