### ISSUE TITLE
How to trigger an event when player actually plays a note?

### ISSUE THREAD

**Issue by wrcstewart** [surikov/webaudiofont#79]
Hi again,
I'm wondering if there is a way to get an event that fires when a note actually plays or close to when the note plays? I would like to show a text version of the pitch on the screen synchronised with the playing. Thanks in advance for any help you can offer.
Cheers
William

**Comment by surikov** [comment]
You send the player the exact start time and duration of the each note. 
Use this information to show the chord of the notes. 

WebAudioFontPlayer does not dispatch time events because you yourself know the exact time of each note.
