### ISSUE TITLE
The pitch slides data structure

### ISSUE THREAD

**Issue by wrcstewart** [surikov/webaudiofont#82]
Hi again,
I was wondering if there is any documentation on the pitch slides parameter or an example?
Thanks in advance for any assistance you can offer.
William

**Comment by wrcstewart** [comment]
Okay
I ve sorted i think
slides = [{ pitch: 60, when = 2] etc
Ty

**Comment by wrcstewart** [comment]
Should have written
when:2

**Comment by surikov** [comment]
yes, the 'slides' parameter is an array of pitch-duration pairs.
Look to source of example at
https://surikov.github.io/webaudiofont/examples/mixer.html
look to slide definition
` [overDrive(D4,1/4,[{when:1/8,pitch:c4}]),bass(B2,1/8),drum()        ,hiHat(), overDrive(A4,1/4,[{when:1/8,pitch:g4}])]	`
