### ISSUE TITLE
How to stop or pause audio

### ISSUE THREAD

**Issue by etayluz** [surikov/webaudiofont#87]
After scheduling a series of notes to play with `player.queueWaveTable`, how do I pause or stop the audio if need be?

Should I use `player.cancelQueue` or `envelope.cancel`? What is the difference?

**Comment by surikov** [comment]
read old answer
https://github.com/surikov/webaudiofont/issues/62

read docs
https://surikov.github.io/webaudiofont/npm/src/docs/classes/player.WebAudioFontPlayer.html#cancelQueue
https://surikov.github.io/webaudiofont/npm/src/docs/modules/otypes.html#WaveEnvelope
