### ISSUE TITLE
a way of querying it for the current audio context time

### ISSUE THREAD

**Issue by etayluz** [surikov/webaudiofont#88]
Tone.js has a way of querying it for the current audio context time
https://tonejs.github.io/docs/14.7.33/fn/now

Does webaudiofont have a similar feature?
Is there really no way to synchronize the app's UI with this library?

**Comment by surikov** [comment]
See examples at
https://github.com/surikov/webaudiofont#example-apps

All of them synchronize the music with the user interface.

Read previous answers.
Please don't create a new issue with the same question.
