### ISSUE TITLE
Velocity and round robnin support

### ISSUE THREAD

**Issue by alfedukovich** [surikov/webaudiofont#91]
Does the player and format support samples library with beat velocity and random selection from several of the same samples?

**Comment by surikov** [comment]
The player supports volume changeing and sample selection.
See https://surikov.github.io/webaudiofont/npm/src/docs/classes/player.WebAudioFontPlayer.html#queueWaveTable

Please be more specific.

**Comment by alfedukovich** [comment]
Velocity is the force of the impact. Roughly speaking, the volume of playback is not changed by decreasing the volume, but by a sample with a recorded attack of lesser force. More relevant for percussion instruments.

Round robin or random is a way of selecting a sample from a pool of the same samples for the same velocity value. Round robin is round robin - it is a round robin of samples. Random - selecting a random one. Also more relevant for percussion instruments or short monotonous sounds. It is used to make consecutive sounds seem less robotic.

Both of these parameters are used in open formats [sfz](https://sfzformat.com/legacy/) and [dspreset](https://www.decentsamples.com/docs/format-documentation.html#appendix-c-boilerplate-dspreset-file) and many other proprietary formats. I don't know if these options are available in sf2?

**Comment by surikov** [comment]
Use different presets if you need different sounds.
