### ISSUE TITLE
Continue playing even if the browser tab is not in focus

### ISSUE THREAD

**Issue by page200** [surikov/webaudiofont#92]
Is there a way to continue playing the music even if the browser tab is not in focus? Maybe by using some kind of more aggressive playback technology.

**Comment by surikov** [comment]
Browser manufacturers force background pages to reduce resource consumption. 
This is the rule for all browsers. 
I don't want to fight browser makers.

**Comment by alfedukovich** [comment]
Use setTimeout or setInterval to queue ahead until the queue finishes playing. Then playback won't stop when you switch tabs.
[code](https://jsbin.com/wuxilab/2/edit?html,output)
[code](https://jsbin.com/cozitux/edit?html,output)

**Comment by page200** [comment]
Thank you, that example indeed works and uses `setInterval`, and the variant with `setTimeout` works as well. `setInterval` or `setTimeout` seem nice for auto-repeating the song for an unlimited number of times.

On the other hand, for each playthrough of a song, I wonder whether anything speaks against simply setting [`stepDuration`](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/examples/midiplayer.html#L56) to the song duration, i.e. queueing the entire song via `queueWaveTable()` at once. The notes are then scheduled [here](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/npm/src/player.ts#L135-L136) via the [`start()` method of an `AudioBufferSourceNode`](https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/start), so the browser makers decide what to do with that, and we're not fighting them. (For now. :))

**Comment by page200** [comment]
Setting a long [`stepDuration`](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/examples/midiplayer.html#L56) works in Firefox and for some MIDI files in Chrome. For other MIDI files in Chrome, the audio stops after a second. Maybe Chrome is stupid in that it focuses on computing something too early for future sounds instead of playing imminent sounds as intended (like Firefox does).

Maybe instead of a long [`stepDuration`](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/examples/midiplayer.html#L56), each step should be called by setTimeout instead of window.requestAnimationFrame.

**Comment by page200** [comment]
Setting a long [`stepDuration`](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/examples/midiplayer.html#L56) works in Firefox and for some MIDI files in Chrome. For other MIDI files in Chrome, the audio stops after a second. Maybe Chrome is stupid in that it focuses on computing something too early for future sounds instead of playing imminent sounds as intended (like Firefox does).

Instead of a long [`stepDuration`](https://github.com/surikov/webaudiofont/blob/8d3bbebcb1b3fa5642b931bf1eff9e7740795c51/examples/midiplayer.html#L56), what seems to work is to call each step with `window.setTimeout` instead of `window.requestAnimationFrame`. Both are unnecessarily resource-intensive except if `setTimeout` takes into account when the next note will actually play instead of getting called every 10 milliseconds.
