### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by soegaard** [surikov/webaudiofont#98]
**Describe the bug**
The page https://surikov.github.io/webaudiofont/#typescript links to
https://github.com/yw662/webaudiofont-ts but the latter shows an 404 page.

**To Reproduce**
1. Go to https://surikov.github.io/webaudiofont/#typescript links to
2. Click on [TypeScript implementation](https://github.com/yw662/webaudiofont-ts)

**Comment by surikov** [comment]
removed
